version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - local-travelpoints-network

  user-service:
    container_name: user-service-container
    image: user-service
    build:
      context: user-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - local-travelpoints-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/user_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints

  review-service:
    container_name: reviews-service-container
    image: review-service
    build:
      context: review-service
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - redis
    networks:
      - local-travelpoints-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/review_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  attraction-service:
    container_name: attraction-service-container
    image: attraction-service
    build:
      context: attraction-service
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    networks:
      - local-travelpoints-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/attraction_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints
    env_file:
      - ../.env

  chat-service:
    container_name: chat-service-container
    image: chat-service
    build:
      context: chat-service
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    networks:
      - local-travelpoints-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/chat_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
    networks:
      - local-travelpoints-network

networks:
  local-travelpoints-network:
    name: local-travelpoints-network
    driver: bridge
