services:
  user-service:
    container_name: user-service-container
    image: user-service
    expose:
      - "80"
      - "8080"
    ports:
      - "8081:8080"
    networks:
      - local-travelpoints-network
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: database-1.crk4ggmecmeg.eu-central-1.rds.amazonaws.com
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: travelpoints

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - local-travelpoints-network
    depends_on:
      - user-service

networks:
  local-travelpoints-network:
    driver: bridge