services:
  user-service:
    container_name: user-service-container
    image: user-service
    expose:
      - "80"
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - local-travelpoints-network
    build:
      context: user-service
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/user_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints

  review-service:
    container_name: reviews-service-container
    image: review-service
    expose:
      - "80"
      - "8083"
    ports:
      - "8083:8083"
    networks:
      - local-travelpoints-network
    build:
      context: review-service
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/review_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints

  attraction-service:
    container_name: attraction-service-container
    image: attraction-service
    expose:
      - "80"
      - "8082"
    ports:
      - "8082:8082"
    networks:
      - local-travelpoints-network
    build:
      context: attraction-service
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/attraction_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints
    env_file:
      - ../.env

  chat-service:
    container_name: chat-service-container
    image: chat-service
    expose:
      - "80"
      - "8084"
    ports:
      - "8084:8084"
    networks:
      - local-travelpoints-network
    build:
      context: chat-service
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travelpoints.crk4ggmecmeg.eu-central-1.rds.amazonaws.com:3306/chat_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: travelpoints

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - local-travelpoints-network
    depends_on:
      - user-service

networks:
  local-travelpoints-network:
    name: local-travelpoints-network
    driver: bridge