name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Docker"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login to docker hub
        run: echo ${{secrets.DOCKER_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Pull User Service Docker Image from HUB
        run: sudo docker pull floareoctavian/userservice:latest & sudo docker pull floareoctavian/travelpoints-nginx:latest
      - name: Delete old docker containers
        run: sudo docker rm -f $(sudo docker ps -a -q) || true
      - name: Run Docker Container
        run: |
          sudo docker run -d -p 8080:8080 --name user-service-container --network travelpoints-network floareoctavian/userservice & 
          sudo docker run -d --name nginx-container --network travelpoints-network -p 80:80 floareoctavian/travelpoints-nginx &
          




    

