name: CI Docker 

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build User Service Docker Image
      run: docker build -t floareoctavian/userservice ./microservices-parent/user-service
    - name: Build NGINX Docker Image
      run: docker build -t floareoctavian/travelpoints-nginx ./microservices-parent/nginx

    - name: Push NGINX to DockerHub
      run: docker push floareoctavian/travelpoints-nginx:latest
    - name: Push to DockerHub
      run: docker push floareoctavian/userservice:latest




