name: CI Docker 

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Load .env file
      uses: goanpeca/setup-envfile@v1
      with:
        envfile: .env
    - name: Login Dockerhub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - name: Build User Service Docker Image
      run: docker build -t travelpoints/user-service ./microserices-parent/user-service/Dockerfile
    - name: Push to DockerHub
      run: docker push travelpoints/user-service:latest
      
